# 应用服务 WEB 访问端口
server:
  port: 8081
constants:
# 应用名称
spring:
  application:
    name: mshivebackend
  # 数据源
  data:
#   	mongodb:
#   		# 主机地址
#   		host: localhost
#   		# 数据库
#   		database: yourdatabase
#   		# 默认端口是27017
#   		port: 27017
# 			# 用子账号
#   		username: test
# 			# 用子密码
#   		password: test
#   		#也可以使用uri连接
# 		    uri: mongodb://192.168.40.134:27017/articledb
  datasource:
    # 数据库驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称，地址，账号，密码
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/blue?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false
    username: root
    password: root
    # 连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
  # java mail
  mail:
    host: smtp.qq.com
    protocol: smtps
    username: 2479711422@qq.com
    password: hyfaxtomhlniebdi
    port: 465
    properties:
      mail:
        smtp:
          socketFactort:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  # redis相关
  redis:
    host: localhost
    port: 6379
    password: root
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
# 下面这些内容是为了让MyBatis映射
# 指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*xml
  # 指定Mybatis的实体目录
  type-aliases-package: com.yimingliao.mshivebackend.entity
# mybatis-plus配置
mybatis-plus:
  # 别名扫描包
  type-aliases-package: com.yimingliao.entity
  configuration:
    # 在映射实体或属性时，将数据表名与字段名的下划线去掉，按照驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
# 输出日志等级
logging:
# 	# 分组
#   group:
#     ebank: com.yimingliao.mshivebackend.controller,com.yimingliao.mshivebackend.service,com.yimingliao.mshivebackend.entity
  level:
    # root为本机调试时的输出等级
    root:
    # ebank 为实际生产时的输出等级
    ebank: debug
#   pattern:
#     dateformat: MM-dd HH:mm:ss:SSS
#     rolling-file-name: MshiveServer.%d{yyyy-MM-dd}.%i.log # 滚动日志
#   file:
#     path: C:\Users\Lenovo\Desktop\MshiveServer\Mshive # 输出地址
#    name: MshiveServer.log
#     max-size: 1KB # 滚动大小
