# 应用服务 WEB 访问端口
server:
  port: 8081
constants:
    server-name: MsHive
# 应用名称
spring:
  application:
    name: mshivebackend
  # 数据源
  data:
    mongodb:
      authentication-database: admin
      authSource: admin
      # 主机地址
      host: localhost
      # 数据库
      database: mshive
      # 默认端口是27017
      port: 27017
      # 用子账号
      username: admin
      # 用子密码
      password: root
      # 也可以使用uri连接
#       uri: mongodb://admin:root@localhost:27017/mshive?authSource=admin&authentication-database=admin
  datasource:
    # 数据库驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称，地址，账号，密码
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/blue?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false
    username: root
    password: root
    # 连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
  # java mail 避免邮件发送工具类写错MailSender，会和JavaMail包里的重名，从而冲突
  mail:
    host: smtp.qq.com
    protocol: smtps
    username: 123456789@qq.com
    password: ndqpxqduiqpc
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  # redis相关
  redis:
    host: localhost
    port: 6379
    password: root
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  # elasticsearch related
#   elasticsearch:
#     username: my-username
#     password: my-password
    # es url
#     uris: http://serverurl:9200
    # connection timeout, default: 1s
#     connection-timeout: 10s
    # data reading timeout, default: 30s
#     socket-timeout: 30s
# 下面这些内容是为了让MyBatis映射
# 指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*xml
  # 指定Mybatis的实体目录
  type-aliases-package: com.yimingliao.mshivebackend.entity
# mybatis-plus配置
mybatis-plus:
  # 别名扫描包
  type-aliases-package: com.yimingliao.entity
  configuration:
    # 在映射实体或属性时，将数据表名与字段名的下划线去掉，按照驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
# 输出日志等级
logging:
# 	# 分组
#   group:
#     ebank: com.yimingliao.mshivebackend.controller,com.yimingliao.mshivebackend.service,com.yimingliao.mshivebackend.entity
  level:
    # root为本机调试时的输出等级，默认info
    root: info
    # ebank 为实际生产时的输出等级
    ebank: debug
#   pattern:
#     dateformat: MM-dd HH:mm:ss:SSS
#     rolling-file-name: MshiveServer.%d{yyyy-MM-dd}.%i.log # 滚动日志
#   file:
#     path: C:\Users\Lenovo\Desktop\MshiveServer\Mshive # 输出地址
#    name: MshiveServer.log
#     max-size: 1KB # 滚动大小
